apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.front.appName }}-service
spec:
  selector:
    app: {{ .Values.front.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.front.servicePort }}
      targetPort: {{ .Values.front.containerPort }}
  type: ClusterIP