name: On code change
on:
    pull_request:
        types: [opened, reopened, synchronize]
jobs:
    static-analysis:
        name: Static Analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              shell: bash
              run: npm install
            - name: Run linter
              shell: bash
              run: npm run lint
    test:
      needs: static-analysis
      name: Unit test
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - name: Install dependencies
            shell: bash
            run: npm install
          - name: Run tests
            shell: bash
            run: npm run test:ci
          - uses: actions/upload-artifact@v4
            with:
              name: unit-test-report
              path: ./html
    build:
        needs: test
        name: build the project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Login to docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build the docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/devops_front:${{ github.head_ref }}


            
