on:
    pull_request:
        types: [opened, reopened, synchronize]
jobs:
    static-analysis:
        name: Static Analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              shell: bash
              run: npm install
            - name: Run linter
              shell: bash
              run: npm run lint
    build:
        needs: static-analysis
        name: build the project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              shell: bash
              run: npm install
            - name: Build project
              shell: bash
              run: npm run build
            - uses: actions/upload-artifact@v3
              with:
                name: build
                path: .
    test:
        needs: build
        name: Unit test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: build
                path: .
            - name: Run tests
              shell: bash
              run: npm run test:unit

            
