name: On merge
on:
    push:
        branches: main

jobs:
    static-analysis:
        name: Static Analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              shell: bash
              run: npm install
            - name: Run linter
              shell: bash
              run: npm run lint
    build:
        needs: static-analysis
        name: build the project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              shell: bash
              run: npm install
            - name: Build project
              shell: bash
              run: npm run build
            - uses: actions/upload-artifact@v4
              with:
                name: build-artifacts
                path: ./dist
    test:
        needs: build
        name: Unit test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              shell: bash
              run: npm install
            - name: Run tests
              shell: bash
              run: npm run test:ci
            - uses: actions/upload-artifact@v4
              with:
                name: unit-test-report
                path: ./html